#!/bin/bash

in_dir=/glade/p/work/edrenkar/MODELS/CCS/RUNS/CCS-LD.HCo02Y
in_dir=/glade/p/work/edrenkar/MODELS/CCS/RUNS/CCS-LD.FCo017

for mon in $( seq -f %02g 1 12 ) ; do
    echo $mon  
    #ncra -O -h $in_dir/monthly_means/????/CCS-LD.HCo02Y_????-${mon}.nc $in_dir/CCS-LD.HCo02Y_clim_${mon}.nc
    ncra -O -h $in_dir/monthly_means/????/CCS-LD.FCo017_????-${mon}.nc $in_dir/CCS-LD.FCo017_clim_${mon}.nc
done
