#!/bin/bash
fyear=1980
lyear=2010
for year in $(seq $fyear $lyear) ; do
    for mon in  $(seq -f "%02g" 1 12); do
        for var in d2 msl precip radlw radsw t2 u10 v10; do
            ncfil=./Forecast/$year/${var}_ERAinterim_${year}_$mon.nc.sub
            if [ ! -f "$ncfil" ]; then
               echo "download:" $year $mon $var
            fi
        done
    done
done
