#!/bin/bash

# CHEYENNE 
SOSIE=/glade/u/home/edrenkar/TOOLS/sosie/bin
dirin=/glade/work/edrenkar/external_data/CCMP
dirmask=/glade/work/edrenkar/external_data/CCMP/land-sea_mask

# MACBOOK
#SOSIE=/Users/elizabethdrenkard/TOOLS/sosie/bin
#dirin=/Users/elizabethdrenkard/TOOLS/CCS_scripts/CCMP

#SWFSC
#SOSIE=/Users/liz.drenkard/TOOLS/sosie/bin
#dirin=/Users/liz.drenkard/external_data/ERAinterim/Forecast/climatologies

dirout=$dirin

ncvar=("Uwind" "Vwind")
yr=MAY01-APR02
for varstr in Uwind Vwind; do

    filin=CCMP_${yr}_${varstr}.nc
    echo $varstr
    filout=$filin

    # DROWN CCMP FILES
    timevar=$( ncdump -h $dirin/$filin | grep time | head -1 | awk '{ print $1 }' )
    ncvar=$( ncdump -h $dirin/$filin | grep float | tail -1 | sed -e "s/(/ /" | awk '{ print $2 }' )

    echo Processing variable $ncvar in file $filin
    $SOSIE/mask_drown_field_era.x -D -i $dirin/$filin -v $varstr -t $timevar \
                                     -m $dirmask/CCMP_LSM.nc\
                                     -p -1 -o $dirout/drowned_$filout  

    # REMOVES THE VARIABLES: VALID_MIN AND VALID_MAX. 
    # ANYTHING EXCEEDING THESE VALUES GETS FILLED/treated as 0

    ncatted -O -a valid_range,,d,, $dirout/drowned_$filout $dirout/drowned_$filout
    ncatted -O -a valid_min,,d,, -a valid_max,,d,, $dirout/drowned_$filout $dirout/drowned_$filout

done

python edit_drowned_CCMP_files.py


