#!/bin/bash

# REMOVES THE VARIABLES: VALID_MIN AND VALID_MAX. 
# ANYTHING EXCEEDING THESE VALUES GETS FILLED/treated as 0
ncfil=/glade/p/work/edrenkar/external_data/CCMP/CCMP_MAY01-APR02_daily_anom.nc 

ncatted -O -a valid_min,,d,, -a valid_max,,d,, $ncfil $ncfil




