#!/bin/bash

# LENS DIRECTORY
dir=/glade/collections/cdg/data/cesmLE/CESM-CAM5-BGC-LE

# MODEL: OCEAN, ATMOSPHERE, ICE
mod_comp=ocn
#mod_comp=atm
#mod_comp=ice

# TYPE OF TIMESERIES
dir2=proc/tseries
tim_range=monthly

# HISTORICAL FORCING INFO
his_bas=b.e11.B20TRC5CNBDRD.f09_g16

# COLDEST, WARMEST, MIDDLE
#runs="6 16 33"
runs="17"

# --- OCEAN ---------------------
vars="SSH TEMP SALT UVEL VVEL PREC_F"
#vars="diatChl spChl diazChl"

# --- ATMOS ---------------------
#vars="PSL TREFHT FLDS FSDS"
#vars="U V Q" # BOTTOM LAYER

# --- ICE -----------------------
#vars=Qref
#vars="TAUX TAUY"

# NOTE: ICE for reference against "bottom layer" variables which are NOT at 10m
for run in $runs; do
    runstr=$(printf %03d $run)

    echo $runstr
    for var in $vars; do
        # ICE 
        #filnm=$dir/$mod_comp/$dir2/$tim_range/$var/${his_bas}.$runstr.cice.h.${var}_nh.192001-200512.nc

        # OCEAN
        filnm=$dir/$mod_comp/$dir2/$tim_range/$var/${his_bas}.${runstr}.pop.h.${var}.192001-200512.nc

        # ATMOSPHERE
        #filnm=$dir/$mod_comp/$dir2/$tim_range/$var/${his_bas}.$runstr.cam.h0.$var.192001-200512.nc

        echo $filnm
        #FOR 1850-2005 RUN ONLY
        #strt_val=1572
        #strt_val= #1950

        #FOR 1920-2005 RUNS
        strt_val=732

        for mon in {1..12}; do
            monstr=$(printf %02d $mon)
            echo $monstr

            # ICE: Qref TAUX TAUY (for check against bottom level atm vars)
            #ncra -O -d time,$strt_val,,12 -d nj,,45 -d ni,200,254 $filnm ./his_${runstr}/${var}_81-05_clim_$monstr.nc

            # OCEAN: SSH TEMP SALT UVEL VVEL PREC_F (SSH and PREC_F are surf but not using z_t_150m as depth dim)
            ncra -O -d time,$strt_val,,12 -d nlat,240,319 -d nlon,190,269 $filnm ./his_${runstr}/${var}_81-05_clim_$monstr.nc

            # SURF OCEAN: CHL
            # ncra -O -d time,$strt_val,,12 -d z_t_150m,0 -d nlat,240,319 -d nlon,190,269 $filnm ./his_${runstr}/${var}_81-05_clim_$monstr.nc

            # ATMOS 2D: PSL TREFHT FLDS FSDS
            #ncra -O -d time,$strt_val,,12 -d lat,110,159 -d lon,160,209 $filnm ./his_${runstr}/${var}_81-05_clim_$monstr.nc

            # ATMOS 3D: U V Q
            #ncra -O -d lev,-1 -d time,$strt_val,,12 -d lat,110,159 -d lon,160,209 $filnm ./his_${runstr}/${var}_81-05_clim_$monstr.nc

            ((strt_val+=1))

        done

        ncrcat -O ./his_${runstr}/${var}_81-05_clim_??.nc ./his_017/${mod_comp}_run${runstr}_${var}_81-05_clim.nc
        rm ./his_${runstr}/${var}_81-05_clim_??.nc
    done
done

