#!/bin/bash

dir=/glade/p/cesmLE/CESM-CAM5-BGC-LE
# OCEAN OR ATMOS MODEL
#mod_comp=ocn
mod_comp=atm
#mod_comp=ice

dir2=proc/tseries
tim_range=monthly

# COLDEST, WARMEST, MIDDLE
#runs="6 16 33"
runs="17"
# --- OCEAN ---------------------
#vars="SSH TEMP SALT UVEL VVEL PREC_F"
#vars="SALT UVEL VVEL PREC_F"
#vars="PREC_F"
# --- ATMOS ---------------------
#vars="PSL TREFHT FLDS FSDS"
vars="U V Q" # BOTTOM LAYER
# --- ICE -----------------------
#vars=Qref
#vars="TAUX TAUY"

for run in $runs; do
    runstr=$(printf %03d $run)

    echo $runstr
    for var in $vars; do
        #filnm1=/glade/p/cesmLE/CESM-CAM5-BGC-LE/$mod_comp/proc/tseries/monthly/$var/b.e11.BRCP85C5CNBDRD.f09_g16.$runstr.cice.h.${var}_nh.200601-208012.nc
        #filnm2=/glade/p/cesmLE/CESM-CAM5-BGC-LE/$mod_comp/proc/tseries/monthly/$var/b.e11.BRCP85C5CNBDRD.f09_g16.$runstr.cice.h.${var}_nh.208101-210012.nc
        #filnm1=/glade/p/cesmLE/CESM-CAM5-BGC-LE/ocn/proc/tseries/monthly/$var/b.e11.BRCP85C5CNBDRD.f09_g16.$runstr.pop.h.$var.200601-208012.nc
        #filnm2=/glade/p/cesmLE/CESM-CAM5-BGC-LE/ocn/proc/tseries/monthly/$var/b.e11.BRCP85C5CNBDRD.f09_g16.$runstr.pop.h.$var.208101-210012.nc
        #filnm1=/glade/p/cesmLE/CESM-CAM5-BGC-LE/atm/proc/tseries/monthly/$var/b.e11.BRCP85C5CNBDRD.f09_g16.$runstr.cam.h0.$var.200601-208012.nc
        #filnm2=/glade/p/cesmLE/CESM-CAM5-BGC-LE/atm/proc/tseries/monthly/$var/b.e11.BRCP85C5CNBDRD.f09_g16.$runstr.cam.h0.$var.208101-210012.nc
        #ls $filnm1
        #strt_val1=840
        #strt_val2=0

        # for mon in {1..12}; do
        #    monstr=$(printf %02d $mon)
        #    echo $monstr
            # ICE
            # ncrcat -O -d time,$strt_val1,,12 -d nj,,45 -d ni,200,254 $filnm1 ${var}_200601-208012_RCP85_$monstr.nc
            # ncrcat -O -d time,$strt_val2,,12 -d nj,,45 -d ni,200,254 $filnm2 ${var}_208101-210012_RCP85_$monstr.nc
        
            # OCEAN
            # ncrcat -O -d time,$strt_val1,,12 -d nlat,240,319 -d nlon,190,269 $filnm1 ${var}_200601-208012_RCP85_$monstr.nc
            # ncrcat -O -d time,$strt_val2,,12 -d nlat,240,319 -d nlon,190,269 $filnm2 ${var}_208101-210012_RCP85_$monstr.nc

            # ATMOS 2D
            #ncrcat -O -d time,$strt_val1,,12 -d lat,110,159 -d lon,160,209 $filnm1 ${var}_200601-208012_RCP85_$monstr.nc
            #ncrcat -O -d time,$strt_val2,,12 -d lat,110,159 -d lon,160,209 $filnm2 ${var}_208101-210012_RCP85_$monstr.nc

            # ATMOS 3D
            # ncrcat -O -d lev,-1 -d time,$strt_val1,,12 -d lat,110,159 -d lon,160,209 $filnm1 ${var}_200601-208012_RCP85_$monstr.nc
            # ncrcat -O -d lev,-1 -d time,$strt_val2,,12 -d lat,110,159 -d lon,160,209 $filnm2 ${var}_208101-210012_RCP85_$monstr.nc

            # ((strt_val1+=1))
            # ((strt_val2+=1))
 
            # ncra -O ${var}_*_RCP85_$monstr.nc ${runstr}/${var}_RCP85_${runstr}_76-00_clim_$monstr.nc
            # rm ${var}_*_RCP85_$monstr.nc 
        #done
        ncrcat -O ./$runstr/${var}_RCP85_${runstr}_76-00_clim_??.nc ./$runstr/${mod_comp}_run${runstr}_${var}_RCP85_76-00_clim.nc
#        ls ${mod_comp}_run${runstr}_${var}_RCP85_76-00_clim.nc
#        rm ${var}_RCP85_76-00_clim_??.nc
    done

done

