#!/bin/bash

dir=/glade/p/cesmLE/CESM-CAM5-BGC-LE
mod_comp=atm
dir2=proc/tseries
tim_range=monthly
vars="OCNFRAC"

strt_val=1572

for var in $vars; do

     filnm=/glade/p/cesmLE/CESM-CAM5-BGC-LE/$mod_comp/proc/tseries/monthly/$var/b.e11.B20TRC5CNBDRD.f09_g16.001.cam.h0.$var.185001-200512.nc
     ncra -O -d time,$strt_val, -d lat,110,159 -d lon,160,209 $filnm ${var}_81-05_mean.nc

done

