#!/bin/bash

#dir=/glade/p/work/edrenkar/external_data/LENS
dir=.
# COLDEST, WARMEST, MIDDLE
# runs="6 16 33"
runs="16"
# --- VARIABLES ---------------------
vars="SSH TEMP SALT UVEL VVEL" # PREC_F PSL TREFHT FLDS FSNS U V Q"
# vars="PSL TREFHT FLDS FSNS U V Q PREC_F"
vars="Qref"
vars="TAUX TAUY"
vars="Uwind Vwind"
runstr=$(printf %03d $runs)
for var in $vars; do
    his_fil=$dir/his/${var}_81-05_clim.nc
    echo $his_fil
    run_fil=$dir/$runstr/${var}_${runstr}_76-00_clim.nc
    echo $run_fil
    ncdiff -O -v $var $run_fil $his_fil $dir/difs/${runstr}_${var}_clim_delta.nc
    
#    for mon in {1..12}; do
#        monstr=$(printf %02d $mon)
#        his_fil=$dir/his/${var}_81-05_clim_$monstr.nc
#        echo $his_fil 
#        for run in $runs; do
#            runstr=$(printf %03d $run)
#            run_fil=$dir/$runstr/${var}_RCP85_${runstr}_76-00_clim_${monstr}.nc 
#            ncdiff -O -v $var $run_fil $his_fil $dir/difs/${runstr}_${var}_${monstr}_delta.nc
#            ncrcat -O $dir/difs/${runstr}_${var}_??_delta.nc $dir/difs/${runstr}_${var}_clim_delta.nc 
#        done
#    done
done
