#!/bin/bash
for year in $( seq -f %04g 1981 2009 ) ; do
    for mon in $( seq -f %02g 1 12 ) ; do

        ncra SST_?m_${year}_${mon}.nc AVHRR_SST_avg_${year}_${mon}.nc
        #rm SST_??_${mon}_clim.nc

    done
done

