#!/bin/bash

n=1
for yr in {2001..2002}; do
    echo $yr

    if (($yr < 1985 )); then
       url=ftp://podaac-ftp.jpl.nasa.gov/allData/avhrr/L3/pathfinder_v51/monthly/day/04km/
       hdf_fil=s04m3pfv51-bsst
    else
       url=ftp://podaac-ftp.jpl.nasa.gov/allData/avhrr/L3/pathfinder_v5/monthly/day/04km/
       if   (($yr > 2006)); then
          hdf_fil=s04m3pfrt-bsst
       elif (($yr > 2001)); then
          hdf_fil=s04m3pfv50-bsst
       else
          hdf_fil=s04m3pfv50-bsst-16b
       fi
    fi

    for mon in {1..12} ; do
        monstr=$(printf %02d $mon)
        echo $monstr
        ncfil=SST_${yr}_$monstr.nc

        #WEGET
        wget $url/$yr/$monstr/$yr$monstr.$hdf_fil.hdf

        #CONVERT TO .hdf to .nc        
        ncl_convert2nc $yr$monstr.$hdf_fil.hdf
        rm $yr$monstr.$hdf_fil.hdf       
        mv $yr$monstr.$hdf_fil.nc $ncfil

        #ADD TIMEDIM
        ncap2 -s "defdim(\"time\",1,0);time[time]=$n;time@long_name=\"Time\";BSST[time,lat,lon]=bsst" -O $ncfil
        ncks -x -v bsst -O $ncfil $ncfil

        #CUT FILESIZE 
        ncks -d lat,600,2000 -d lon,400,2000 -O $ncfil $ncfil
        ((n+=1))
    done
done

#for mon in {1..12} ; do
#    monstr=$(printf %02d $mon)
#    ncra *$monstr.nc SST_am_${monstr}_clim.nc
#    rm *$monstr.nc
#done

